import {
  SiSpringboot,
  SiHibernate,
  SiStreamlit,
  SiMysql,
  SiPostgresql,
  SiPhp,
  SiHtml5,
  SiCss as SiCss3,
  SiGit,
  SiGithub,
  SiPython,
  SiCplusplus,
  SiFigma,
  SiApachemaven as SiMaven,
  SiEclipseide,
  SiJavascript,
  SiMake,
  SiGooglecloud,
  SiGmail,
  SiGooglecalendar,
  SiN8N,
  SiClaude,
  SiOpenai,
  SiGooglegemini,
  SiPerplexity,
} from 'react-icons/si'
import { FaJava, FaReact, FaDatabase, FaServer, FaChartLine, FaMobileAlt, FaMicrochip, FaBolt, FaTerminal } from 'react-icons/fa'
import { VscVscode } from 'react-icons/vsc'

// Maps the `icon` key from data/skills.js to an actual icon component.
// Centralizing this here means SkillCard.jsx doesn't need a giant if/else —
// it just looks up iconMap[key].
export const iconMap = {
  java: FaJava,
  javascript: SiJavascript,
  python: SiPython,
  sql: FaDatabase,
  cpp: SiCplusplus,
  springboot: SiSpringboot,
  hibernate: SiHibernate,
  react: FaReact,
  streamlit: SiStreamlit,
  api: FaServer,
  analytics: FaChartLine,
  figma: SiFigma,
  server: FaServer,
  make: SiMake,
  ghl: FaBolt,
  googlecloud: SiGooglecloud,
  gmail: SiGmail,
  googlecalendar: SiGooglecalendar,
  n8n: SiN8N,
  claude: SiClaude,
  claudecode: FaTerminal,
  chatgpt: SiOpenai,
  codex: SiOpenai,
  gemini: SiGooglegemini,
  perplexity: SiPerplexity,
  git: SiGit,
  github: SiGithub,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  html5: SiHtml5,
  css3: SiCss3,
  php: SiPhp,
  responsive: FaMobileAlt,
  iot: FaMicrochip,
  eclipse: SiEclipseide,
  vscode: VscVscode,
  maven: SiMaven,
}
